# Generated by Django 3.2.7 on 2023-03-29 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0005_customer_customer_order_deliveryaddress_order_orderitem_product_routedetails_shop_order_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('contactnumber', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('jobtitle', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Cook', 'Cook'), ('Helper', 'Helper'), ('Rider', 'Rider')], max_length=100, null=True)),
                ('basicsalary', models.FloatField(default=0, null=True)),
                ('othours', models.FloatField(default=0, null=True)),
                ('otrate', models.FloatField(default=0, null=True)),
                ('allowances', models.FloatField(default=0, null=True)),
                ('netsalary', models.FloatField(default=0, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
